[env:esp32dev] ; (o el nombre de la placa que tengas configurada)
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Agrega estas líneas de abajo:
lib_deps =
    knolleary/PubSubClient@^2.8.0
	paulstoffregen/OneWire
	milesburton/DallasTemperature
	bblanchon/ArduinoJson
	